=== AnonymerNiklasistanonym/privacy-visualization-of-a-decentralized-ride-pooling-platform/simulation/config.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$ref": "#/definitions/SimulationConfigCustom",
    "definitions": {
        "SimulationConfigCustom": {
            "type": "object",
            "properties": {
                "authenticationService": {
                    "type": "object",
                    "properties": {
                        "count": {
                            "type": "number"
                        }
                    },
                    "required": [
                        "count"
                    ],
                    "additionalProperties": false
                },
                "matchingService": {
                    "type": "object",
                    "properties": {
                        "count": {
                            "type": "number"
                        }
                    },
                    "required": [
                        "count"
                    ],
                    "additionalProperties": false
                },
                "customer": {
                    "type": "object",
                    "properties": {
                        "count": {
                            "type": "number"
                        }
                    },
                    "required": [
                        "count"
                    ],
                    "additionalProperties": false
                },
                "rideProvider": {
                    "type": "object",
                    "properties": {
                        "countPerson": {
                            "type": "number"
                        },
                        "countCompany": {
                            "type": "number"
                        },
                        "countCompanyFleet": {
                            "type": "number"
                        }
                    },
                    "required": [
                        "countPerson",
                        "countCompany",
                        "countCompanyFleet"
                    ],
                    "additionalProperties": false
                },
                "locations": {
                    "type": "array",
                    "items": {
                        "anyOf": [
                            {
                                "$ref": "#/definitions/SimulationConfigCity"
                            },
                            {
                                "$ref": "#/definitions/SimulationConfigBBox"
                            }
                        ]
                    }
                },
                "startPos": {
                    "type": "object",
                    "properties": {
                        "lat": {
                            "type": "number",
                            "description": "Latitude"
                        },
                        "long": {
                            "type": "number",
                            "description": "Longitude"
                        }
                    },
                    "required": [
                        "lat",
                        "long"
                    ],
                    "additionalProperties": false
                },
                "port": {
                    "type": "number"
                },
                "cacheDir": {
                    "type": "string"
                },
                "customPathfinder": {
                    "type": "string",
                    "enum": [
                        "pathfinder-server",
                        "all"
                    ]
                },
                "ignoreCache": {
                    "type": "boolean"
                },
                "$schema": {
                    "type": "string"
                }
            },
            "additionalProperties": false
        },
        "SimulationConfigCity": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string",
                    "const": "city"
                },
                "name": {
                    "type": "string"
                },
                "countryCode": {
                    "type": "string"
                }
            },
            "required": [
                "countryCode",
                "name",
                "type"
            ],
            "additionalProperties": false
        },
        "SimulationConfigBBox": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string",
                    "const": "bbox"
                },
                "minLat": {
                    "type": "number"
                },
                "maxLat": {
                    "type": "number"
                },
                "minLong": {
                    "type": "number"
                },
                "maxLong": {
                    "type": "number"
                }
            },
            "required": [
                "maxLat",
                "maxLong",
                "minLat",
                "minLong",
                "type"
            ],
            "additionalProperties": false
        }
    }
}

=== AnonymerNiklasistanonym/privacy-visualization-of-a-decentralized-ride-pooling-platform/simulation/config_small.json
{
    "$schema": "./config.schema.json",
    "locations": [{
        "type": "bbox",
        "minLat": 48.65,
        "minLong": 9.05,
        "maxLat": 48.70,
        "maxLong": 9.10
    }],
    "rideProvider": {
        "countPerson": 5,
        "countCompany": 0,
        "countCompanyFleet": 0
    },
    "customer": {
        "count": 5
    },
    "authenticationService": {
        "count": 1
    },
    "matchingService": {
        "count": 1
    }
}
